clear variables; close all;

fname = 'src/model-comparison.csv';
data = importfile(fname);

xnames = {'log-log', 'exp-exp', 'log-exp', 'log-log', 'exp-exp' ,'log-exp', 'log-log', 'exp-exp', 'log-exp'};
tstring = {'East', 'North', 'Up'};
%% 3 coordinates
for j = 0:2
    % selection
    data1 = data(1:3+j:end, :);
    % plot
%     figure
%     boxplot([data1.rms15w, data1.rms15w1, data1.rms15w2 ...
%         data1.rms1y, data1.rms1y1, data1.rms1y2 ...
%         data1.rms2y, data1.rms2y1, data1.rms2y2 ...
%         data1.rms, data1.rms1, data1.rms2])
    
    figure('position',[118,556,560,245])
    boxplot([data1.rms15w, data1.rms15w1, data1.rms15w2, ...
        data1.rms2y, data1.rms2y1, data1.rms2y2 , ...
        data1.rms, data1.rms1, data1.rms2], ...
        'labels', xnames)
    
    % Change the boxplot color from blue to green
    a = get(get(gca,'children'),'children');   % Get the handles of all the objects
    t = get(a,'tag');   % List the names of all the objects
    for i = 0:2
        box1 = a(19+i);   % The 7th object is the first box
        set(box1, 'Color', 'g');   % Set the color of the first box to green
        
        box2 = a(22+i);   % The 7th object is the first box
        set(box2, 'Color', 'm');   % Set the color of the first box to green
        
    end
    set(gca, 'YGrid', 'on', 'XGrid', 'off')
    title(tstring{j+1}, 'FontWeight', 'Normal')
    ylabel('RMS [mm]')
    
end

%% statistics (bar)
for j = 0:2
    figure
    data1 = data(1:3+j:end, :);
    m15w= mean(data1{:,3:4:end});
    m1y = mean(data1{:,4:4:end});
    m2y = mean(data1{:,5:4:end});
    m   = mean(data1{:,6:4:end});
    
    M = [m15w; m1y; m2y; m];
    bar(M, 'BaseValue', 1.5)
    
end

%% 
function modelcomparison = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  MODELCOMPARISON = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  MODELCOMPARISON = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  modelcomparison = importfile("C:\Users\david\Documents\ma2020\ma2020-dgfi-dw\src\model-comparison.csv", [3, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 29-Sep-2020 00:08:37

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [3, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 14);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "rms15w", "rms1y", "rms2y", "rms", "rms15w1", "rms1y1", "rms2y1", "rms1", "rms15w2", "rms1y2", "rms2y2", "rms2"];
opts.VariableTypes = ["categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
opts = setvaropts(opts, 1, "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
modelcomparison = readtable(filename, opts);

end